-- lost-astronaut · seed: 3 Venture Builder rubrics + 10 candidates across the pipeline.
-- Run against a fresh DB after 0001_create_candidates_and_rubrics.sql.

-- ===== Rubrics (Venture Builder, v1, active) =====
insert into rubrics (kind, version, business_model, content, is_active, source, notes) values
('ranking', 1, 'venture_builder',
 '{"title":"Venture Builder - Candidate Ranking Rubric v1","adjacent_space":"<<FILL IN via /config: describe Lost Astronaut''s space + must-have domain criteria>>","output":"Return rank_score 0-100 and a concise rank_reason.","weights":{"seniority_leadership":0.20,"builder_track_record":0.25,"domain_fit_adjacent_space":0.20,"availability_openness":0.15,"pedigree_ex_jobs_universities_ventures":0.10,"social_presence":0.10},"signals":{"seniority_leadership":"C-level/VP/founder-level; has led teams or orgs at scale.","builder_track_record":"Has shipped products or built/scaled companies - can build, not just manage.","domain_fit_adjacent_space":"Works in or near our space (see adjacent_space).","availability_openness":"Plausibly movable - between roles, advising, exploring, itch to build.","pedigree":"Ex-jobs/employers, ex-universities, ex-startup-ventures.","social_presence":"Follower counts / online footprint / notability."},"note":"Business model is UNDECIDED (Venture Builder vs Hacker House). Edit weights/criteria here - no code changes."}'::jsonb,
 true, 'seed', 'Seed v1'),
('chat_outcomes', 1, 'venture_builder',
 '{"title":"Venture Builder - Chat Wanted Outcomes v1","goal":"Short qualifying conversation (keep human / max 1-2 messages). Decide yes/no on booking an intro call.","wanted_outcomes":["Confirm genuine interest in building with or for us","Gauge availability and timeline","Surface what they would want to build or contribute","Confirm domain fit"],"guardrail":"Do NOT run an automated persuasion bot - a fully automated bot burns good candidates. Flag chat as human in the UI."}'::jsonb,
 true, 'seed', 'Seed v1'),
('label', 1, 'venture_builder',
 '{"title":"Venture Builder - Post-Meeting Label Rubric v1","scale":{"green":"Strong fit - pursue.","yellow":"Maybe - revisit later.","red":"Not a fit now."},"inputs":"Combine rank + chat + meeting notes (good/bad/worth-it).","fit_track":"Also capture the track: recruit | co_found | build_for | none.","override":"Ilona''s manual verdict ALWAYS overrides the computed label.","note":"Label is POST-MEETING only - never label someone not yet met."}'::jsonb,
 true, 'seed', 'Seed v1');

-- ===== 10 candidates spread across the pipeline =====
insert into candidates
 (linkedin_url, full_name, headline, current_company, current_title, company_domain,
  background, social, current_focus, signals, rank_score, rank_reason,
  status, swipe_decision, computed_label, label_reason, ilona_verdict, verdict_reason,
  fit_track, reentry_reason, next_review_at, source, meeting_notes, chat_transcript)
values
('https://www.linkedin.com/in/maya-chen-demo','Maya Chen','Former VP Engineering at Stripe','Independent','Building something new',null,
 '{"ex_employers":["ex-Stripe","ex-Google"],"education":["Stanford MS CS"],"ex_ventures":["Founded Cohort, acquired 2021"],"notable":["Scaled payments infra to 4B GMV"]}'::jsonb,
 '{"x":{"handle":"@mayacodes","followers":18400},"linkedin":{"followers":12000},"footprint":"Conference speaker, 2 patents"}'::jsonb,
 'Exploring AI infra ideas','{"availability":"Left Stripe 3 months ago","openness":"Posting about next chapter"}'::jsonb,
 null,null,'sourced','pending',null,null,null,null,null,null,null,'openoutreach',null,'[]'::jsonb),
('https://www.linkedin.com/in/david-okafor-demo','David Okafor','Ex-AWS Director of Engineering','Independent','Advisor',null,
 '{"ex_employers":["ex-AWS","ex-Microsoft"],"education":["MIT BS EECS"],"ex_ventures":["Co-founded Lumen Labs"],"notable":["Led 200-person org"]}'::jsonb,
 '{"x":{"handle":"@dokafor","followers":7400},"linkedin":{"followers":21000}}'::jsonb,
 'Advising early-stage infra startups','{"availability":"Open to founding role","openness":"Actively networking"}'::jsonb,
 82,'Strong builder + leadership pedigree; high domain adjacency; clearly available.',
 'ranked','pending',null,null,null,null,null,null,null,'openoutreach',null,'[]'::jsonb),
('https://www.linkedin.com/in/priya-raman-demo','Priya Raman','CPO at a fintech scale-up','NimbusPay','Chief Product Officer','nimbuspay.com',
 '{"ex_employers":["ex-Revolut","ex-McKinsey"],"education":["LBS MBA","IIT Bombay"],"ex_ventures":["Founded PayNimbus (seed)"],"notable":["0-1 product leader"]}'::jsonb,
 '{"linkedin":{"followers":33000},"footprint":"Newsletter 15k subscribers"}'::jsonb,
 'Leading product at current company','{"availability":"Curious, not actively looking","openness":"Replied warmly"}'::jsonb,
 88,'Exceptional 0-1 product + founder track; large following; availability uncertain.',
 'in_review','pending',null,null,null,null,null,null,null,'openoutreach',null,'[]'::jsonb),
('https://www.linkedin.com/in/elena-vasquez-demo','Elena Vasquez','Founder and ex-CTO (acquired)','Independent','Founder',null,
 '{"ex_employers":["ex-Datadog"],"education":["CMU MS"],"ex_ventures":["Founded Verda (acq by Datadog)"],"notable":["Built and sold an observability startup"]}'::jsonb,
 '{"x":{"handle":"@elenav","followers":42000},"linkedin":{"followers":28000}}'::jsonb,
 'Between things post-acquisition','{"availability":"Earnout ended, free","openness":"Wants to build again"}'::jsonb,
 91,'Proven builder-to-exit, deeply technical, available and hungry. Top of cohort.',
 'approved','approved',null,null,null,null,null,null,null,'openoutreach',null,'[]'::jsonb),
('https://www.linkedin.com/in/james-whitfield-demo','James Whitfield','VP Product at a marketplace unicorn','Bazaar','VP Product','bazaar.com',
 '{"ex_employers":["ex-Airbnb","ex-Uber"],"education":["Wharton MBA"],"ex_ventures":[],"notable":["Scaled marketplace to 50 markets"]}'::jsonb,
 '{"linkedin":{"followers":17000}}'::jsonb,
 'VP Product role','{"availability":"Open to chat","openness":"Accepted connection"}'::jsonb,
 79,'Strong operator pedigree; less hands-on building; solid adjacency.',
 'invited','approved',null,null,null,null,null,null,null,'openoutreach',null,'[]'::jsonb),
('https://www.linkedin.com/in/aisha-mohammed-demo','Aisha Mohammed','Co-founder and CEO, dev-tools startup','ShipYard','Co-founder and CEO','shipyard.dev',
 '{"ex_employers":["ex-GitHub"],"education":["Oxford"],"ex_ventures":["Founded ShipYard (Series A)"],"notable":["Technical founder"]}'::jsonb,
 '{"x":{"handle":"@aisham","followers":31000},"linkedin":{"followers":19000}}'::jsonb,
 'Running ShipYard','{"availability":"Exploring what is next quietly","openness":"In conversation"}'::jsonb,
 85,'Technical repeat founder, strong following, adjacent domain.',
 'in_chat','approved',null,null,null,null,null,null,null,'openoutreach',null,
 '[{"role":"operator","text":"Loved what you built at ShipYard - open to a quick chat about what is next?"},{"role":"candidate","text":"Always happy to chat. What did you have in mind?"}]'::jsonb),
('https://www.linkedin.com/in/kenji-tanaka-demo','Kenji Tanaka','Ex-CTO, AI research lab','Independent','Founder',null,
 '{"ex_employers":["ex-DeepMind","ex-Google Brain"],"education":["Tokyo University PhD","Stanford postdoc"],"ex_ventures":["Founded Synaptic (seed)"],"notable":["20+ papers, applied ML"]}'::jsonb,
 '{"x":{"handle":"@ktanaka","followers":54000},"linkedin":{"followers":26000},"footprint":"Cited researcher"}'::jsonb,
 'Winding down Synaptic','{"availability":"Open to co-found","openness":"Booked intro call"}'::jsonb,
 90,'Elite research + founder pedigree, big following, perfectly adjacent. Call booked.',
 'meeting_booked','approved',null,null,null,null,null,null,null,'openoutreach',null,
 '[{"role":"operator","text":"Would love to compare notes - grabbed a slot on Calendly."},{"role":"candidate","text":"Booked. Looking forward to it."}]'::jsonb),
('https://www.linkedin.com/in/robert-kline-demo','Robert Kline','COO at a B2B SaaS company','LedgerLoop','Chief Operating Officer','ledgerloop.com',
 '{"ex_employers":["ex-Salesforce","ex-Oracle"],"education":["Kellogg MBA"],"ex_ventures":[],"notable":["Scaled revenue operations"]}'::jsonb,
 '{"linkedin":{"followers":9000}}'::jsonb,
 'COO role','{"availability":"Comfortable, exploratory","openness":"Took the call"}'::jsonb,
 77,'Strong operator, weaker on hands-on building; moderate adjacency.',
 'met','approved',null,null,null,null,null,null,null,'openoutreach',
 '{"good":["Sharp on go-to-market","Deep operations experience"],"bad":["Not a builder, more execution","Comp expectations high"],"worth_it":"Maybe as an operating partner, not a co-founder"}'::jsonb,
 '[]'::jsonb),
('https://www.linkedin.com/in/sophia-laurent-demo','Sophia Laurent','Repeat founder, climate-tech','Independent','Founder',null,
 '{"ex_employers":["ex-Tesla"],"education":["Polytechnique","Stanford MS"],"ex_ventures":["Founded two startups, one exit"],"notable":["Hardware + software founder"]}'::jsonb,
 '{"x":{"handle":"@slaurent","followers":38000},"linkedin":{"followers":24000}}'::jsonb,
 'Scouting next venture','{"availability":"Free and motivated","openness":"Very engaged"}'::jsonb,
 86,'Repeat founder with an exit, strong following, motivated.',
 'labeled','approved','green','Rank + chat + meeting all strongly positive.','green','Confirmed - ideal co-founder profile, move forward.',
 'co_found',null,null,'openoutreach',
 '{"good":["Visionary and technical","Ready to start now","Values aligned"],"bad":["Wants significant equity"],"worth_it":"Yes - strong co-founder candidate"}'::jsonb,
 '[]'::jsonb),
('https://www.linkedin.com/in/marcus-feld-demo','Marcus Feld','Senior Director, enterprise infra','CoreStack','Senior Director','corestack.io',
 '{"ex_employers":["ex-VMware","ex-Cisco"],"education":["Georgia Tech"],"ex_ventures":[],"notable":["Enterprise infra leader"]}'::jsonb,
 '{"linkedin":{"followers":6000}}'::jsonb,
 'Senior Director role, not ready to move','{"availability":"Happy in current role for now","openness":"Warm but timing off"}'::jsonb,
 73,'Solid pedigree but limited building track; timing not right.',
 'holding','approved',null,null,null,null,null,'warm_goodbye', now() + interval '90 days','openoutreach',null,
 '[{"role":"operator","text":"Totally understand the timing - can I check back in a quarter?"},{"role":"candidate","text":"Please do, lets reconnect then."}]'::jsonb);
